version: '3'

services:
  app1:
    build:
        context: .
        dockerfile: app1_Dockerfile
    ports:
        - "5001:5001"
  app2:
    build:
        context: .
        dockerfile: app2_Dockerfile
    ports:
        - "5002:5002"
  app3:
    build:
        context: .
        dockerfile: app3_Dockerfile
    ports:
        - "5003:5003"
  app4:
    build:
        context: .
        dockerfile: app4_Dockerfile
    ports:
        - "5004:5004"
    cap_drop:
        - ALL
  app5:
    build:
        context: .
        dockerfile: app5_Dockerfile
    ports:
        - "5005:5005"
    cap_drop:
        - ALL
  app6:
    build:
        context: .
        dockerfile: app6_Dockerfile
    ports:
        - "5006:5006"
